# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: uni_v3
rollback_on_reorg: true
unordered_multichain_mode: true
preload_handlers: true
contracts:
  - name: UniswapV3Pool
    handler: src/EventHandlers.ts
    events:
      - event: Mint(address sender, address indexed owner, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount, uint256 amount0, uint256 amount1)
      - event: Burn(address indexed owner, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount, uint256 amount0, uint256 amount1)

networks:
  - id: 1 # Ethereum Mainnet
    start_block: 0
    contracts:
      - name: UniswapV3Pool
        address:
          - 0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8
          - 0xe6ff8b9a37b0fab776134636d9981aa778c4e718
          - 0x56534741cd8b152df6d48adf7ac51f75169a83b2
          - 0x99ac8ca7087fa4a2a1fb6357269965a2014abc35
